import { Router, type IRouter } from "express";
import accountsRouter from "./accounts";
import healthRouter from "./health";
import productsRouter from "./products";
import customersRouter from "./customers";
import repsRouter from "./reps";
import purchasesRouter from "./purchases";
import salesRouter from "./sales";
import inventoryRouter from "./inventory";
import expensesRouter from "./expenses";
import treasuryRouter from "./treasury";
import reportsRouter from "./reports";
import suppliersRouter from "./suppliers";
import employeesRouter from "./employees";
import attendanceRouter from "./attendance";
import payrollRouter from "./payroll";
import costCentersRouter from "./costCenters";
import repCustodyRouter from "./repCustody";
import obligationsRouter from "./obligations";
import authRouter from "./auth";
import adminAuthRouter from "./adminAuth";
import repPortalRouter from "./repPortal";
import operationalCostsRouter from "./operationalCosts";
import settingsRouter from "./settings";
import journalRouter from "./journal";
import warehousesRouter from "./warehouses";
import purchaseReturnsRouter from "./purchaseReturns";
import saleReturnsRouter from "./saleReturns";
import purchaseOrdersRouter from "./purchase-orders";

const router: IRouter = Router();

router.use(accountsRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(adminAuthRouter);
router.use(settingsRouter);
router.use(repPortalRouter);
router.use(operationalCostsRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(repsRouter);
router.use(purchasesRouter);
router.use(salesRouter);
router.use(inventoryRouter);
router.use(expensesRouter);
router.use(treasuryRouter);
router.use(reportsRouter);
router.use(suppliersRouter);
router.use(employeesRouter);
router.use(attendanceRouter);
router.use(payrollRouter);
router.use(costCentersRouter);
router.use(repCustodyRouter);
router.use(obligationsRouter);
router.use(journalRouter);
router.use(warehousesRouter);
router.use(purchaseOrdersRouter);
router.use(purchaseReturnsRouter);
router.use(saleReturnsRouter);

export default router;
